Remove dataproc from MakeSiteOnlyVcf
populationgenomics/production-pipelines pull request #626
Opened 2024-02-21 22:18 UTC by michael-harper

This pull request aims to address concerns regarding the dependency on Dataproc for the MakeSiteOnlyVcf stage of large cohort processing. See this Slack thread [here](https://centrepopgen.slack.com/archives/C018KFBCR1C/p1708485526044469).

Moving this job away from non-preemptible machines within Dataproc to pre-emptible machines in QoB raises concerns about the risk of process failure due to the potentially extended processing times for large datasets. Nonetheless, it seems possible to remove dataproc from this stage.

Note: An alternative is to move towards Hail's ability to conduct parallel exports during VCF merging that would help nullify the pre-emption issue. Although integrating parallel exports into the pipeline may be complex, it could significantly optimise the process and eliminate the need for Dataproc.

2024-02-27 22:08 UTC, michael-harper commented
**Note**: The output Hail Tables of dataproc (dp) vs. no-dataproc (no-dp) are different. The `AS_FS` field appears to be different between dp and no-dp. At first it was thought that this was due to a stochastic nature of the FisherStrand variable however, when comparing two no-dp `site_only.ht` files (see screenshot below cell [4]) there appears to be no difference (the `no_path_no_dp_site_only_ht` was a result of a second no-dp test to test whether `Path` or `str` variables had to be passed - turns out `str` variables are required!). 

<img width="1882" alt="Screenshot 2024-02-28 at 9 01 50 am" src="https://github.com/populationgenomics/production-pipelines/assets/109899932/d5d90f77-1452-4936-ab21-add42b0be7ce">

I've included the full output of the comparison as a txt file
[MakeSiteOnlyVcf_dp_vs_nodp_comparison.txt](https://github.com/populationgenomics/production-pipelines/files/14426263/MakeSiteOnlyVcf_dp_vs_nodp_comparison.txt)

2024-03-12 04:57 UTC, vivbak requested changes

2024-03-12 04:57 UTC, vivbak commented on cpg_workflows/stages/large_cohort.py
> +            # if not vds_version.startswith('v'):
Could we please revert this in this PR? All good if we end up going for this change, but it's outside the scope and should be introduced in a separate PR :)

2024-04-01 23:34 UTC, michael-harper commented
Running again to check if same inputs generate different outputs. This is to check if the AS_FS field has a random component.

Two batches here: 

    https://batch.hail.populationgenomics.org.au/batches/438609/jobs/1

    https://batch.hail.populationgenomics.org.au/batches/438612/jobs/1 

The output of the above batches are the same, suggesting that the AS_FS field does not change due to randomness and the change in output detected is likely due to Dataproc and non-Dataproc usage.
<img width="917" alt="Screenshot 2024-04-02 at 10 20 53 AM" src="https://github.com/populationgenomics/production-pipelines/assets/109899932/3d28892c-0053-4432-8cf2-9c46b6cfb589">


(Note: both run2_no_dp_siteonly and run2_no_dp_siteonly2 use the same inputs, also note that these outputs are the same as gs://cpg-bioheart-test/large_cohort/3-0/no_dp_site_only.ht)

2024-04-30 23:40 UTC, michael-harper commented
We are content with the current differences between using Dataproc and not using Dataproc. The difference seems to be due to the way math is happening (see [Zulip chat here](https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/Difference.20between.20dataproc.20and.20non-dataproc.20output/near/433256063)). This change can be merged

2024-04-30 23:47 UTC, vivbak approved these changes

2024-05-01 00:45 UTC, merged