Remove Dataproc from Frequencies stage of Large Cohort
populationgenomics/production-pipelines pull request #632
Opened 2024-02-29 03:37 UTC by michael-harper

First attempt not using dataproc, changing stage output to tmp bucket for testing purposes as well

2024-02-29 05:35 UTC, michael-harper commented
<img width="889" alt="Screenshot 2024-02-29 at 4 28 33 pm" src="https://github.com/populationgenomics/production-pipelines/assets/109899932/9d59614e-9ae2-4c85-8a41-37626a49c98a">

2024-03-12 05:00 UTC, vivbak requested changes
Pausing this merge until the linter issues resolve.

2024-04-30 22:34 UTC, michael-harper commented
@vivbak I've rebased this branch, ready for a re-review post linter issues

2024-04-30 23:47 UTC, vivbak approved these changes

2024-05-01 03:24 UTC, merged